# Generated by Django 5.1.5 on 2025-01-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Montenegro Slay!', max_length=255),
        ),
    ]
